//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZpiCapgeminiProduction5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRACZ
    {
        public GRACZ()
        {
            this.POTYCZKI = new HashSet<POTYCZKI>();
        }
    
        public string Login { get; set; }
        public string Hasło { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string E_mail { get; set; }
    
        public virtual ICollection<POTYCZKI> POTYCZKI { get; set; }
    }
}
